# Generated by Django 2.2.2 on 2019-06-06 11:46

from django.db import migrations

sql = """UPDATE django_content_type
         SET app_label = 'a4_candy_questions'
         WHERE app_label = 'a4-speakup_questions';"""

reverse_sql = """UPDATE django_content_type
                 SET app_label = 'a4-speakup_questions';
                 WHERE app_label = 'a4_candy_questions';"""

class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_questions', '0002_question_category'),
    ]

    operations = [
        migrations.RunSQL(sql, reverse_sql)
    ]
