# Generated by Django 2.2.2 on 2019-06-13 13:30

from django.db import migrations


def rename_app(apps, schema_editor):
    Phase = apps.get_model("a4phases", "Phase")
    for phase in Phase.objects.all():
        phase.type = phase.type.replace(
            'a4-speakup',
            'a4_candy')
        phase.save()


def backname_app(apps, schema_editor):
    Phase = apps.get_model("a4phases", "Phase")
    for phase in Phase.objects.all():
        phase.type = phase.type.replace(
            'a4_candy',
            'a4-speakup')
        phase.save()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('a4_candy_questions', '0004_rename_table'),
        ('a4phases', '0006_remove_weight_from_phase_type')
    ]

    operations = [
        migrations.RunPython(rename_app, backname_app)
    ]
