# Generated by Django 2.2.3 on 2019-08-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_questions', '0005_rename_app_in_phase_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='is_favourite',
            new_name='is_on_shortlist',
        ),
    ]
