# Generated by Django 2.2.3 on 2019-08-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_questions', '0006_rename_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
