# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('a4-speakup_likes', '0002_add_related_name')]

    dependencies = [
        ('a4_candy_likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_likes', to='a4_candy_questions.Question'),
        ),
    ]
