# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('a4-speakup_likes', '0003_unique_together')]

    dependencies = [
        ('a4_candy_questions', '0002_question_category'),
        ('sessions', '0001_initial'),
        ('a4_candy_likes', '0002_add_related_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('session', 'question')]),
        ),
    ]
