# Generated by Django 2.2.2 on 2019-06-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_likes', '0005_update_content_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table=None,
        ),
    ]
